#!/bin/sh
set -eu

cargo fmt --all --check
cargo clippy --workspace --all-targets
cargo clippy --workspace --all-targets --all-features
cargo test --workspace --all-targets --all-features
cargo doc --workspace --all-features --no-deps
